### PR TITLE
Add SPL Token support

### PR DESCRIPTION
**Pull request by t-nelson**
In an effort to speed review here, I thought I'd draft what I have.  We can at least bikeshed the display strings :slightly_smiling_face: 

Running the first ten integration tests will flex most of the display strings.  

TODO
- [x] Add support for CreateAccountWithSeed variants
- [x] Multisig integration test variants
- [x] More tests
- [ ] ~Support displaying all signer pubkeys instead of "m of n" string (not actually sure we have SRAM to do this easily)~ ENOMEM

### CODE REVIEW

**Comment by garious** [comment]
Exceptional quality as usual. Looks great!

**Comment by t-nelson** [comment]
This is ready for final review!

I bailed on displaying the individual signers since it's going to take another RAM belt-tightening pass, which will be non-trivial

**Comment by garious** [comment]
Display string nits:

Pretty verbose "SPL Token transfer" and is the only place we see "SPL". How about "Transfer tokens"? And perhaps "Transfer" can be changed to "Transfer SOL", in which case you'd remove the SOL suffix from the number.  Removing that suffix would lead to less scrolling, which would be good too.

"Of mint" -> "From mint"?

Old issue, should purge the term custodian. "Lockup custodian" -> "Lockup auth"

**Comment by garious** [comment]
Also, can you add `cargo clippy` to CI for the `tests` directory? A bunch of `&vec![]` garbage in there.

**Comment by t-nelson** [comment]
I've addressed the display nits.  I went with "Transfer" > "System transfer" (or "Deposit" in the case of account creation) for now.  This is because all of the SOL "amount" displays sit behind a `summary_item_set_amount()` call which assumes a "SOL" suffix on the amount rather than the title and some of the other places it's used have long titles that will be truncated with an appended suffix. I do agree this is the right way forward.  IIRC, if we can get a bug fixed in the Nano S SDK and unbold the second text line, the largest possible SOL amount will fit without scrolling at all.

I'll follow up with cargo clippy + fmt for CI in another PR

**Comment by garious** [comment]
I don't care for "System transfer". We don't expose the name of the System program to the user anywhere else or even in the CLI. Just "Transfer" is fine if SOL is anywhere in the message.

**Pull request merged**
