### PR TITLE
Lift program resolution

### PR DESCRIPTION
**Pull request by t-nelson**
#### Problem

Replicode.  Program resolution happens in the individual instruction parsers

#### Changes

Expose program ID constatnts
Resolve program earlier

### CODE REVIEW

**Comment by garious** [comment]
Valid C, but not sure if global structs are initialized. Can you sanity-check this change on device before merging?

**Comment by t-nelson** [comment]
It had passed both integration and a few manual local cluster transfers
before a round of cosmetic cleanups.  I'll send it through integration
again in the morning to be sure.  Anything more specific to check?

**Comment by garious** [comment]
After reading the BOLOS docs, I was under the impression globals, like the Pubkey constants, wouldn't be initialized.  I might have read that wrong.

**Comment by t-nelson** [comment]
[This](https://ledger.readthedocs.io/en/0/bolos/application_structure.html#pic-and-model-implications) is the closest I recall to anything about global constants, but it refers to storing pointers and the nuances around PIC.  I'd be pretty surprised if there was a decision to strictly ignore/omit static initializations. Not _zeroing_ uninitialized globals on the other hand I could see

I reran integration, paying close attention that the transfer and stake delegation transactions were indeed correctly identified and that the garbage sign transaction was unrecognized. :heavy_check_mark:

**Comment by garious** [comment]
:shipit:

**Comment by garious** [comment]
crap, I approved too soon.  Why did you make it so it only works with one instruction?

**Comment by garious** [comment]
nm, I see what you're doing.  calling that variable `first_instruction` instead of `instruction` would have made it obvious.  No action needed.

**Comment by t-nelson** [comment]
I didn't.  I just didn't extend it to multiple, yet.  That's where I'm headed :slightly_smiling_face:

**Pull request merged**
