### PR TITLE
Use Ledger's devenv

### PR DESCRIPTION
**Pull request by t-nelson**
#### Problem

Tracking master from Ledger's fork requires that we use their devenv, which we currently are not

#### Changes

Use it

### CODE REVIEW

**Comment by garious** [comment]
This works on macos?

**Comment by t-nelson** [comment]
Ah right, I knew there was _something_ we still needed Vagrant for.  Will rework

**Comment by t-nelson** [comment]
Ok.  Reinstated a tweaked Vagrant config

**Comment by t-nelson** [comment]
Worst part was the 3hrs where I was only getting ~20kbps on a 200MB do download :sweat_smile:

**Pull request merged**
