### PR TITLE
Add Rust tests

### PR DESCRIPTION
**Pull request by CriesofCarrots**

### CODE REVIEW

**Comment by garious** [comment]
Maybe we need that CI!

```
cargo test
   Compiling hidapi v1.1.1
error: failed to run custom build command for `hidapi v1.1.1`

Caused by:
  process didn't exit successfully: `/vagrant/rust-tests/target/debug/build/hidapi-1786e10bb586be5b/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'Unable to find libudev: Command { command: "\"pkg-config\" \"--libs\" \"--cflags\" \"libudev\"", cause: Os { code: 2, kind: NotFound, message: "No such file or directory" } }', src/libcore/result.rs:1188:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

**Comment by garious** [comment]
fixed in https://github.com/solana-labs/ledger-app-solana/pull/8

**Comment by CriesofCarrots** [comment]
Thanks!
Hmm, I wonder how I managed to get through a full `vagrant destroy; vagrant up; cargo test` without running into this. I have more to learn about vagrant caching, I guess.

**Comment by garious** [comment]
Weird. That should have been sufficient.

**Pull request merged**
